[Settings]
Priority=Default
Properties=MyCustomProperty

[Default]
; --- CREDENCIALES PARA CONECTAR AL SERVIDOR ---
; (Esto evita que te pida usuario/pass al principio de la instalación)
UserID=carlos
UserDomain=DESPLIEGUE
UserPassword=Admin123

; --- CONTRASEÑA DEL ADMINISTRADOR LOCAL ---
; (La que quieres que tenga el equipo una vez instalado)
AdminPassword=Admin123

; --- INICIO DE SESIÓN AUTOMÁTICO ---
; Esto es vital para que se instalen las aplicaciones solo
AutoLogon=YES
AutoLogonCount=2

; --- CONFIGURACIÓN DE DRIVERS (TOTAL CONTROL) ---
DriverGroup001=Windows 11\%Make%\%Model%

; --- CONFIGURACIÓN GENERAL ---
PowerShellShellExecutionPolicy=Bypass
OSInstall=Y
SkipCapture=YES
SkipAdminPassword=YES
SkipProductKey=YES
SkipComputerBackup=YES

; --- CONFIGURACIÓN BITLOCKER (AUTOMÁTICO AL AD) ---
SkipBitLocker=YES
BDEInstallSuppress=NO
BDEInstall=TPM
BDERecoveryKey=AD
BDEWait=YES

; Ocultar bienvenida (IP) y teclado español
SkipBDDWelcome=YES
KeyboardLocale=es-ES
UserLocale=es-ES
UILanguage=es-ES

; Ocultar migración de datos
SkipUserData=YES

; Ocultar Idioma y Zona Horaria (España)
SkipLocaleSelection=YES
SkipTimeZone=YES
TimeZoneName=Romance Standard Time

; Ocultar Roles
SkipRoles=YES

; Pantallas que sí quieres ver
SkipTaskSequence=NO
SkipComputerName=NO
SkipDomainMembership=NO
SkipApplications=NO
SkipFinalSummary=NO

; --- CONFIGURACIÓN WSUS (LOCAL) ---
; Apunta a tu nuevo servidor para que la Task Sequence no salga a Internet
WSUSServer=http://SRV-DESPLIEGUE.despliegue.taboas:8530